import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Sparkles, FileText, Download, Save, History, 
  Trash2, Eye, Edit3, Briefcase, User, Calendar, 
  ArrowLeft, RefreshCw, CheckCircle2, AlertCircle, FileSpreadsheet
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import GlassCard from '../../components/ui/GlassCard';
import MagneticButton from '../../components/ui/MagneticButton';
import { motion } from 'framer-motion';

export default function CoverLetterGenerator() {
  const { user } = useAuth();
  
  // Inputs
  const [recipientName, setRecipientName] = useState('Hiring Manager');
  const [companyName, setCompanyName] = useState('Target Company');
  const [jobTitle, setJobTitle] = useState('Software Engineer');
  const [jobDescription, setJobDescription] = useState('');
  
  // Generated and editable content
  const [content, setContent] = useState('');
  const [title, setTitle] = useState('My AI Cover Letter');
  const [letterId, setLetterId] = useState('');

  // UI States
  const [loading, setLoading] = useState(false);
  const [saveLoading, setSaveLoading] = useState(false);
  const [editMode, setEditMode] = useState(true); // true = edit text, false = preview letterhead
  const [templateStyle, setTemplateStyle] = useState('modern'); // 'modern' | 'classic' | 'navy'
  const [toast, setToast] = useState(null);
  
  // History
  const [savedLetters, setSavedLetters] = useState([]);

  const fetchHistory = async () => {
    try {
      const res = await axios.get('/api/coverletters/list');
      setSavedLetters(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const showToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3000);
  };

  // Call Gemini to generate cover letter
  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!jobDescription || !jobDescription.trim()) {
      showToast('Please enter a target job description', 'error');
      return;
    }

    setLoading(true);
    try {
      const res = await axios.post('/api/coverletters/generate', {
        jobDescription,
        recipientName,
        companyName,
        jobTitle
      });
      setContent(res.data.content);
      setTitle(`Cover Letter - ${jobTitle} at ${companyName}`);
      setEditMode(true);
      showToast('Cover letter generated by Gemini!', 'success');
    } catch (err) {
      console.error(err);
      showToast('Failed to generate cover letter.', 'error');
    } finally {
      setLoading(false);
    }
  };

  // Save in MongoDB
  const handleSave = async () => {
    if (!content || !content.trim()) {
      showToast('Generate a cover letter first before saving', 'error');
      return;
    }
    setSaveLoading(true);
    try {
      const payload = {
        id: letterId || null,
        title,
        recipientName,
        companyName,
        jobTitle,
        content
      };
      const res = await axios.post('/api/coverletters/save', payload);
      setLetterId(res.data.id);
      showToast('Cover letter saved successfully!', 'success');
      fetchHistory();
    } catch (err) {
      console.error(err);
      showToast('Failed to save cover letter.', 'error');
    } finally {
      setSaveLoading(false);
    }
  };

  // Load from list
  const handleLoad = (letter) => {
    setLetterId(letter.id);
    setTitle(letter.title);
    setRecipientName(letter.recipientName || 'Hiring Manager');
    setCompanyName(letter.companyName || 'Target Company');
    setJobTitle(letter.jobTitle || 'Software Engineer');
    setContent(letter.content);
    setEditMode(true);
    showToast(`Loaded cover letter for ${letter.companyName}`, 'success');
  };

  // Delete cover letter
  const handleDelete = async (id, e) => {
    e.stopPropagation();
    if (!window.confirm('Are you sure you want to delete this cover letter?')) return;
    try {
      await axios.delete(`/api/coverletters/${id}`);
      showToast('Cover letter deleted successfully', 'success');
      fetchHistory();
      if (letterId === id) {
        setLetterId('');
        setContent('');
        setTitle('My AI Cover Letter');
      }
    } catch (err) {
      console.error(err);
      showToast('Failed to delete cover letter.', 'error');
    }
  };

  // Download Word Doc natively using HTML XML Word wrapper
  const handleDownloadWord = () => {
    if (!content) return;
    const header = "<html xmlns:o='urn:schemas-microsoft-com:office:office' " +
          "xmlns:w='urn:schemas-microsoft-com:office:word' " +
          "xmlns='http://www.w3.org/TR/REC-html40'>" +
          "<head><title>Cover Letter</title><style>body { font-family: Arial, sans-serif; font-size: 11pt; line-height: 1.6; margin: 1in; color: #1e293b; }</style></head><body>";
    const footer = "</body></html>";
    const formattedContent = content.replace(/\n/g, '<br/>');
    const html = header + formattedContent + footer;

    const blob = new Blob(['\ufeff' + html], {
      type: 'application/msword'
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_')}.doc`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleDownloadPDF = () => {
    window.print();
  };

  return (
    <div className="min-h-full flex flex-col items-center px-4 md:px-8 py-8 relative selection:bg-brand-500 selection:text-white print:p-0 print:bg-white print:text-black">
      {/* Glow Blur Details */}
      <div className="absolute top-10 left-1/4 w-80 h-80 bg-brand-500/5 rounded-full blur-[120px] pointer-events-none print:hidden"></div>
      <div className="absolute bottom-10 right-1/4 w-80 h-80 bg-cyan-500/5 rounded-full blur-[120px] pointer-events-none print:hidden"></div>

      {/* Toast Notification */}
      {toast && (
        <div className="fixed bottom-5 right-5 z-50 flex items-center gap-2.5 px-4.5 py-3 rounded-xl border bg-white/[0.03] shadow-2xl border-brand-500/20 print:hidden animate-slide-up">
          {toast.type === 'success' ? (
            <CheckCircle2 className="h-4.5 w-4.5 text-brand-400" />
          ) : (
            <AlertCircle className="h-4.5 w-4.5 text-rose-400" />
          )}
          <span className="text-xs font-semibold text-slate-200">{toast.message}</span>
        </div>
      )}

      <div className="max-w-6xl w-full z-10 flex flex-col print:max-w-full">
        
        {/* Top bar control menu */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 print:hidden">
          <div className="space-y-1 text-left">
            <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight flex items-center gap-2.5">
              <FileSpreadsheet className="h-7 w-7 text-brand-400" />
              <span>AI Cover Letter Generator</span>
            </h1>
            <p className="text-slate-400 text-xs mt-1">
              Draft professional, tailored cover letters matching your resume and target role qualifications.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <input 
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Cover Letter Title..."
              className="bg-white/[0.02] border border-white/[0.05] focus:border-brand-500 text-xs font-semibold text-white px-3 py-2.5 shadow-inner rounded-xl outline-none"
            />
            <button 
              onClick={handleSave}
              disabled={saveLoading || !content}
              className="px-4 py-2.5 bg-white/[0.02] border border-white/[0.05] text-slate-300 hover:text-white hover:bg-white/[0.05] shadow-inner rounded-xl text-xs font-bold transition flex items-center gap-1.5 disabled:opacity-50"
            >
              {saveLoading ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Save className="h-3.5 w-3.5" />}
              <span>Save</span>
            </button>
            <button 
              onClick={handleDownloadWord}
              disabled={!content}
              className="px-4 py-2.5 bg-white/[0.02] border border-white/[0.05] text-slate-300 hover:text-white hover:bg-white/[0.05] shadow-inner rounded-xl text-xs font-bold transition flex items-center gap-1.5 disabled:opacity-50"
            >
              <Download className="h-3.5 w-3.5" />
              <span>DOCX</span>
            </button>
            <button 
              onClick={handleDownloadPDF}
              disabled={!content}
              className="px-5 py-2.5 bg-brand-600 hover:bg-brand-500 text-white font-bold rounded-xl text-xs shadow-[0_0_20px_rgba(59,130,246,0.3)] hover:scale-[1.02] transition flex items-center gap-1.5 disabled:opacity-50"
            >
              <Download className="h-3.5 w-3.5" />
              <span>PDF</span>
            </button>
          </div>
        </div>

        {/* Workspace split grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start print:block print:w-full">
          
          {/* Left panel: generation form - Hidden in print */}
          <div className="lg:col-span-5 space-y-6 print:hidden">
            
            {/* Input fields */}
            <div className="bg-white/[0.03] border border-white/[0.08] shadow-[0_8px_30px_rgb(0,0,0,0.12)] backdrop-blur-xl p-6 rounded-3xl border border-white/[0.05] space-y-4 text-left">
              <h3 className="text-xs font-heading font-black text-white uppercase tracking-widest mb-2">Job Information</h3>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wide">Recipient / Hiring Name</label>
                  <input 
                    type="text"
                    value={recipientName}
                    onChange={(e) => setRecipientName(e.target.value)}
                    placeholder="e.g. Hiring Manager"
                    className="w-full bg-white/[0.02] hover:bg-white/[0.03] border border-white/[0.05] focus:border-brand-500 shadow-inner rounded-xl px-3 py-2.5 text-xs text-white outline-none transition"
                  />
                </div>
                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wide">Company Name</label>
                  <input 
                    type="text"
                    value={companyName}
                    onChange={(e) => setCompanyName(e.target.value)}
                    placeholder="e.g. Google"
                    className="w-full bg-white/[0.02] hover:bg-white/[0.03] border border-white/[0.05] focus:border-brand-500 shadow-inner rounded-xl px-3 py-2.5 text-xs text-white outline-none transition"
                  />
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wide">Job Title / Role</label>
                <input 
                  type="text"
                  value={jobTitle}
                  onChange={(e) => setJobTitle(e.target.value)}
                  placeholder="e.g. Software Engineer"
                  className="w-full bg-white/[0.02] hover:bg-white/[0.03] border border-white/[0.05] focus:border-brand-500 shadow-inner rounded-xl px-3 py-2.5 text-xs text-white outline-none transition"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wide">Job Description</label>
                <textarea 
                  rows="6"
                  value={jobDescription}
                  onChange={(e) => setJobDescription(e.target.value)}
                  placeholder="Paste the target job qualifications or description details..."
                  className="w-full bg-white/[0.02] hover:bg-white/[0.03] border border-white/[0.05] focus:border-brand-500 shadow-inner rounded-xl px-3 py-2 text-xs text-white outline-none transition resize-none font-sans"
                />
              </div>

              <button 
                onClick={handleGenerate}
                disabled={loading}
                className="w-full py-3 bg-brand-600 hover:bg-brand-500 text-white font-bold rounded-2xl text-xs shadow-[0_0_20px_rgba(59,130,246,0.3)] hover:scale-[1.01] transition flex items-center justify-center gap-1.5"
              >
                {loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                <span>{loading ? 'Generating draft...' : 'Generate Cover Letter'}</span>
              </button>
            </div>

            {/* History Sidebar */}
            <div className="bg-white/[0.03] border border-white/[0.08] shadow-[0_8px_30px_rgb(0,0,0,0.12)] backdrop-blur-xl p-6 rounded-3xl border border-white/[0.05] space-y-4 text-left">
              <h3 className="text-xs font-heading font-black text-white uppercase tracking-widest flex items-center gap-1.5">
                <History className="h-4 w-4 text-brand-400" />
                <span>Saved Drafts</span>
              </h3>

              {savedLetters && savedLetters.length > 0 ? (
                <div className="space-y-3">
                  {savedLetters.map((letter) => (
                    <div 
                      key={letter.id}
                      onClick={() => handleLoad(letter)}
                      className={`p-3.5 bg-white/[0.02] border rounded-2xl cursor-pointer hover:border-white/[0.15] transition flex items-center justify-between ${
                        letterId === letter.id ? 'border-brand-500/40' : 'border-white/[0.05]'
                      }`}
                    >
                      <div className="space-y-1">
                        <h4 className="text-xs font-bold text-white truncate max-w-[160px]">{letter.title}</h4>
                        <div className="text-[8.5px] text-slate-500 font-semibold">
                          {new Date(letter.updatedAt || letter.createdAt).toLocaleDateString()}
                        </div>
                      </div>
                      
                      <div className="flex gap-1 shrink-0">
                        <button 
                          className="p-1 hover:bg-slate-800 text-slate-400 rounded-lg transition"
                          title="View Draft"
                        >
                          <Eye className="h-3.5 w-3.5" />
                        </button>
                        <button 
                          onClick={(e) => handleDelete(letter.id, e)}
                          className="p-1 hover:bg-red-500/10 text-slate-500 hover:text-rose-400 rounded-lg transition"
                          title="Delete Draft"
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-6 text-slate-650 text-xs font-medium">
                  No saved drafts found.
                </div>
              )}
            </div>

          </div>

          {/* Right panel: editor & preview */}
          <div className="lg:col-span-7 print:w-full print:block">
            
            {/* Editor mode toggler - Hidden in print */}
            <div className="flex items-center justify-between mb-4 print:hidden">
              <div className="flex bg-white/[0.03] p-1 rounded-xl gap-1">
                <button 
                  onClick={() => setEditMode(true)}
                  className={`px-3.5 py-1.5 rounded-lg text-xs font-bold transition flex items-center gap-1.5 ${
                    editMode ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
                  }`}
                >
                  <Edit3 className="h-3.5 w-3.5" />
                  <span>Editor</span>
                </button>
                <button 
                  onClick={() => setEditMode(false)}
                  disabled={!content}
                  className={`px-3.5 py-1.5 rounded-lg text-xs font-bold transition flex items-center gap-1.5 ${
                    !editMode ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
                  } disabled:opacity-40`}
                >
                  <Eye className="h-3.5 w-3.5" />
                  <span>Preview letterhead</span>
                </button>
              </div>

              {!editMode && (
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mr-1">Style:</span>
                  <button 
                    onClick={() => setTemplateStyle('modern')}
                    className={`px-2.5 py-1 text-[10px] font-semibold border rounded-lg transition ${
                      templateStyle === 'modern' ? 'bg-brand-500/10 border-brand-500/20 text-brand-400' : 'border-slate-800 text-slate-400'
                    }`}
                  >
                    Emerald
                  </button>
                  <button 
                    onClick={() => setTemplateStyle('classic')}
                    className={`px-2.5 py-1 text-[10px] font-semibold border rounded-lg transition ${
                      templateStyle === 'classic' ? 'bg-brand-500/10 border-brand-500/20 text-brand-400' : 'border-slate-800 text-slate-400'
                    }`}
                  >
                    Classic
                  </button>
                </div>
              )}
            </div>

            {/* Content body wrapper */}
            {editMode ? (
              <div className="bg-white/[0.03] border border-white/[0.08] shadow-[0_8px_30px_rgb(0,0,0,0.12)] backdrop-blur-xl p-6 rounded-3xl border border-white/[0.05] text-left space-y-4 print:hidden">
                <div className="flex justify-between items-center">
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Cover Letter Editor</span>
                  <span className="text-[9px] text-slate-400 font-medium">Changes here will be saved to your letter draft</span>
                </div>
                <textarea 
                  rows="22"
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  placeholder="Generated cover letter draft will appear here..."
                  className="w-full bg-white/[0.03]/60 border border-white/[0.05] focus:border-brand-500 rounded-2xl px-4 py-3.5 text-xs text-slate-200 outline-none transition font-sans leading-relaxed resize-none"
                />
              </div>
            ) : (
              /* A4 Paper Letterhead Preview */
              <div 
                id="coverletter-printable-area"
                className="w-full min-h-[820px] bg-white text-black p-10 md:p-12 shadow-2xl rounded-2xl relative overflow-hidden flex flex-col justify-between text-left print:shadow-none print:rounded-none"
              >
                <div className="space-y-6 flex-grow">
                  
                  {/* Letterhead top accent line */}
                  {templateStyle === 'modern' && (
                    <div className="h-2 bg-emerald-500 -mx-12 -mt-12 mb-6"></div>
                  )}

                  {/* Header metadata details */}
                  <div className={`pb-6 border-b border-slate-100 flex justify-between items-end ${
                    templateStyle === 'classic' ? 'border-t border-slate-250 pt-4' : ''
                  }`}>
                    <div>
                      <h2 className="text-xl font-black text-slate-900 tracking-tight leading-none">{user?.name || 'Developer Candidate'}</h2>
                      <span className="text-[9px] font-bold text-emerald-600 uppercase tracking-wider mt-1 block">Software Professional</span>
                    </div>
                    <div className="text-right text-[9px] text-slate-500 space-y-0.5 font-sans">
                      <div className="font-semibold text-slate-800">{user?.email || 'email@example.com'}</div>
                      <div>Application Cover Letter</div>
                    </div>
                  </div>

                  {/* Letter body */}
                  <div className="text-[10.5px] leading-relaxed text-slate-700 whitespace-pre-line font-serif pr-2">
                    {content || 'Generate cover letter to preview details.'}
                  </div>

                </div>

                {/* Footer Brand Marker (Hidden in print) */}
                <div className="border-t border-slate-100 pt-3 text-center text-[7px] text-slate-400 font-medium uppercase tracking-widest flex items-center justify-center gap-1.5 print:hidden">
                  <Sparkles className="h-3 w-3 text-emerald-500 animate-pulse" />
                  <span>AI Cover Letter Generator</span>
                </div>

              </div>
            )}

            {/* Empty Editor View */}
            {!content && (
              <div className="bg-white/[0.03] border border-white/[0.08] shadow-[0_8px_30px_rgb(0,0,0,0.12)] backdrop-blur-xl p-16 text-center rounded-3xl border border-white/[0.05] print:hidden">
                <FileText className="h-12 w-12 text-slate-700 mx-auto mb-4" />
                <h4 className="text-base font-bold text-white mb-2">No Letter Generated Yet</h4>
                <p className="text-xs text-slate-500 max-w-xs mx-auto">
                  Paste target job specifications in the left panel to generate a custom-tailored cover letter instantly.
                </p>
              </div>
            )}

          </div>

        </div>

      </div>

      {/* Global CSS inject for print overrides */}
      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          body * {
            visibility: hidden;
            background: white !important;
            color: black !important;
          }
          #coverletter-printable-area, #coverletter-printable-area * {
            visibility: visible;
          }
          #coverletter-printable-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100% !important;
            min-height: 100% !important;
            padding: 0 !important;
            box-shadow: none !important;
            border: none !important;
          }
          .print\\:hidden {
            display: none !important;
          }
        }
      `}} />
    </div>
  );
}
